[tool.poetry]
name = "wsidicom"
version = "0.1.0"
description = "Tools for handling DICOM based whole scan images"
authors = ["Erik O Gabrielsson <erik.o.gabrielsson@sectra.com>"]
license = "Apache 2.0"

[tool.poetry.dependencies]
python = "^3.7"
numpy = "^1.15.0"
pydicom = "^2.1.0"
Pillow = "^8.0.0"

[tool.poetry.dev-dependencies]
pytest = "^6.0.0"
pytest-watch = "^4.2.0"
xmltodict = "^0.12.0"
shapely = "^1.7.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
